version: '3.8'

services:
  front:
    build:
      context: .
      dockerfile: Dockerfile
    image: node-git:dev
    container_name: ${BRANCH:?err}
    environment:
      BRANCH: ${BRANCH:?err}
    volumes:
      - ~/.ssh:/root/.ssh
    ports:
      - ${PORT:-8005}:8000
